-- Display spotify playback in lualine via spt

-- local cached_status = "No music"
-- local update_interval = 10000
--
-- local function update_spotify_status()
-- 	vim.fn.jobstart("spt pb -f '%t - %a'", {
-- 		on_stdout = function(_, data)
-- 			if data and #data > 0 then
-- 				cached_status = data[1]
-- 			end
-- 		end,
--
-- 		stdout_buffered = true,
-- 	})
-- end
--
-- local timer = vim.loop.new_timer()
-- timer:start(0, update_interval, vim.schedule_wrap(update_spotify_status))
--
-- local function spotify_status()
-- 	return cached_status or "No music"
-- end
--
-- return spotify_status
