vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = false
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.autoindent = true
vim.opt.mouse = ""
vim.opt.termguicolors = true
vim.opt.fillchars = { eob = " " }
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.clipboard = "unnamedplus"
vim.opt.updatetime = 50
vim.o.pumheight = 15
vim.o.showmode = false
vim.o.signcolumn = "yes"
vim.g.noshowmode = true
vim.opt.backup = false
vim.opt.wrap = false
vim.opt.cursorline = true
vim.opt.cursorlineopt = "both"
vim.opt.wildignore:append({ "*/node_modules/*" })
